title: Northern SLT
url: 'https://beta.northslt.ca'
baseurl: 'null'
google_analytics_key: 'null'
disqus_shortname: 'null'
newsletter_action: 'null'
logo: /siteicon.png
description: Knowledge base template for Jekyll.
author:
  name: null
  email: null
  twitter: null
social:
  name: Base Template
  links:
    - 'https://github.com/CloudCannon/base-jekyll-template'
timezone: Etc/UTC
permalink: '/:categories/:title/'
plugins:
  - jekyll-extract-element
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
collections:
  sets: null
jekyll-archives:
  enabled:
    - categories
defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      comments: true
  - scope:
      type: sets
    values:
      _hide_content: true
  - scope:
      path: index.html
    values:
      body_class: show_hero_search
      
sass:
    sass_dir: _sass